//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonEmpleadosModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmonEmpleadosEntities : DbContext
    {
        public AdmonEmpleadosEntities()
            : base("name=AdmonEmpleadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleDiaTrabajo> DetalleDiaTrabajoes { get; set; }
        public virtual DbSet<DiaTrabajo> DiaTrabajoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Nivel> Nivels { get; set; }
        public virtual DbSet<Salario> Salarios { get; set; }
        public virtual DbSet<Subsidio> Subsidios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
    }
}
