//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmonEmpleadosModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiaTrabajo()
        {
            this.DetalleDiaTrabajoes = new HashSet<DetalleDiaTrabajo>();
        }
    
        public int id { get; set; }
        public System.DateTime dia { get; set; }
        public double horas { get; set; }
        public string horasExtra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDiaTrabajo> DetalleDiaTrabajoes { get; set; }
    }
}
